In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df_delayed = pd.read_csv(r'C:\Users\gerem\Desktop\datathon-7mlet-grupo-77\data\synthetic_enrichment\delayed_rewards.csv', sep=',')
df_catalog = pd.read_csv(r'C:\Users\gerem\Desktop\datathon-7mlet-grupo-77\data\synthetic_enrichment\offer_catalog.csv', sep=',')
df_events = pd.read_csv(r'C:\Users\gerem\Desktop\datathon-7mlet-grupo-77\data\synthetic_enrichment\offer_events.csv', sep=',')

In [5]:
df_catalog.head()

,arm_id,arm_name,arm_type,description,is_control
0,0,sem_oferta,controle,Grupo controle sem oferta ativa.,True
1,1,educacao_financeira,conteudo,Conteúdo educativo sobre organização financeira.,False
2,2,simulador_credito,ferramenta,Simulador de crédito para avaliar opções dispo...,False
3,3,cartao_premium,produto,Oferta sintética de cartão premium.,False

In [6]:
df_delayed.head()

,event_id,subject_key,occurred_at,channel,arm_id,arm_name,reward,delay_days,reward_observed_at,reward_type,reward_status
0,evt_000001,subject_000001,2025-01-01 00:00:00,whatsapp,0,sem_oferta,0,6,2025-01-07 00:00:00,sem_conversao_observada,not_converted
1,evt_000002,subject_000002,2025-01-01 00:01:00,email,3,cartao_premium,0,4,2025-01-05 00:01:00,sem_conversao_observada,not_converted
2,evt_000003,subject_000003,2025-01-01 00:02:00,whatsapp,2,simulador_credito,0,6,2025-01-07 00:02:00,sem_conversao_observada,not_converted
3,evt_000004,subject_000004,2025-01-01 00:03:00,web,1,educacao_financeira,0,5,2025-01-06 00:03:00,sem_conversao_observada,not_converted
4,evt_000005,subject_000005,2025-01-01 00:04:00,email,1,educacao_financeira,0,4,2025-01-05 00:04:00,sem_conversao_observada,not_converted

In [7]:
df_events.head()

,event_id,subject_key,occurred_at,channel,arm_id,arm_name,reward,idade,profissao,estado_civil,...,numero_contatos_anteriores,resultado_campanha_anterior,taxa_variacao_emprego,indice_preco_consumidor,indice_confianca_consumidor,taxa_euribor_3_meses,numero_empregados,conversao,cliente_ja_contatado,faixa_contatos
0,evt_000001,subject_000001,2025-01-01 00:00:00,whatsapp,0,sem_oferta,0,56,housemaid,married,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,0,1
1,evt_000002,subject_000002,2025-01-01 00:01:00,email,3,cartao_premium,0,57,services,married,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,0,1
2,evt_000003,subject_000003,2025-01-01 00:02:00,whatsapp,2,simulador_credito,0,37,services,married,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,0,1
3,evt_000004,subject_000004,2025-01-01 00:03:00,web,1,educacao_financeira,0,40,admin.,married,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,0,1
4,evt_000005,subject_000005,2025-01-01 00:04:00,email,1,educacao_financeira,0,56,services,married,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,0,1

In [8]:
df_events.shape

(41188, 29)

In [9]:
df_delayed.shape

(41188, 11)